### ISSUE TITLE
Texture Fehler

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#104]
Schaafe, Titenfische und Dorfbewohner (hier aber nicht alle) haben eine komische metallerne und fehlende Textur

**Comment by Tsunayoshi** [comment]
Optifine verursacht den Fehler.
Fehlerhaftes Texturpack oder Problem mit OF selbst

**Comment by Tsunayoshi** [comment]
Betrifft nur Schafen und Skellis/Zombies?

**Comment by Tsunayoshi** [comment]
Auf gut glück mal ein paar Mods deaktivert.
Es können sein. JournyMap, Minechem oder AgriCraft
Nur Agricraft hatte in letzter Zeit ein update. Teste weiter

**Comment by Tsunayoshi** [comment]
Agricraft:
https://github.com/InfinityRaider/AgriCraft/issues/293

**Comment by Tsunayoshi** [comment]
Teste downgrade auf 1.3.1

**Comment by Tsunayoshi** [comment]
1.3.1 startet nicht. Texturfehler wird bleiben mit Agricraft ein update raus bringt

**Comment by Tsunayoshi** [comment]
7.0.2.0
Villager ID auf 12 gesetzt damit kein Absturz beim anladen!
Downgrade behebt texturfehler.
