### ISSUE TITLE
Kompatiblität Rubber zu Sticky Resin

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#106]
Das Rezept für einen Ruberseed (9005) funktioniert mit raw rubber und Ball of Glue, aber nicht mit Sticky Resin (4131). Wäre cool und logisch wenn das auch ginge

**Comment by Tsunayoshi** [comment]
Rezept erstellen. Dann aber für einen ic2 sapling

LG Schuby
(vom Handy versendet)

Am 29.07.2015 um 16:57 schrieb Attachie notifications@github.com:

**Comment by Attachie** [comment]
ic2 Sapling? ne ich meine den seed, nicht sapling. Also für magical crops

**Comment by Tsunayoshi** [comment]
Ah verstehe und stimmt vollkommen

**Comment by Tsunayoshi** [comment]
ic2:sticky sollte zu oredict dazu itemRawRubber

**Comment by Tsunayoshi** [comment]
Update 7.0.5.3
