### ISSUE TITLE
Steel Nugget

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#107]
Wenn man Steel bei botania herstellt bekommt man steel von Mekanism (6049:4). Diesen kann man nicht im crafting Tabel als Nuggets umwandeln. Gewollt?

**Comment by Tsunayoshi** [comment]
Werde das Rezept auf Railcraft nuggets hinzufügen

**Comment by Tsunayoshi** [comment]
Nuggetrezepte entfernt. Somit lässt sich jeder Steel Ingot im Crucible Furnace oder in der Tinkers Schmelze einschmelzen und in Nuggets gießen.
Update 7.0.5.3
