### ISSUE TITLE
Silicon

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#113]
Silicon kann man (neben anderen) im pulverisierer herstellen. Kann man das auch machen, dass man es ebenfalls im Macerator herstellen kann?

**Comment by Tsunayoshi** [comment]
Wird mit Update 7.1.1.8 behoben

**Comment by Tsunayoshi** [comment]
Mine Tweaker funktioniert nicht auf IC2 Maschinen, daher kann ich das nicht beheben
