### ISSUE TITLE
Damascus Steel

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#114]
Es gibt ein rezept für den alloy der mit bronze und eisen dust Damascus herstellt. aber es geht nur mit dem dust von ic2 nich mit dem was bei pulverisierer raus kommt

**Comment by Attachie** [comment]
ok das rezept was angezeigt wirt geht auch nicht.... hab ich den falschen alloy smelter?

**Comment by Tsunayoshi** [comment]
Fehlende Rezepte den Maschinen beibringen

**Comment by Tsunayoshi** [comment]
Uneindeutige Angabe im NEI: Alloy Recipe.
Die Bindung von Damascus an die TSchmelze ist ganz gut. Alternativ muss man die Dusts hestellen. Per crafting mischen und dann im Furnace herstellen.
Rücksprache mit Attachie: ok
