### ISSUE TITLE
Kochen 5 = Butter

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#128]
Linke Seite:
Ein trockenes Brot alleine ist natürlich noch kein tolles Sandwich, mit süßer Butter bestrichen, kommt es einem Sandwich schon näher. Dabei ist es egal ob Erdnuss- Pistazienbutter oder Andere. 

1.Rechte Seite:
Für das Feld eignet sich am besten die Erdnuss.
        2. Aufgabe -> detected 8 Erdnüsse

2.Rechte Seite:
Nun musst du sie kleinmachen. Das geht mit dem Juicer, welchen du natürlich auch super für Fruchtsäfte benutzen kannst. 
2. Aufgabe -> detected 8 Peanut Butter

Belohnung: Saucepan

Verweise:

**Comment by Tsunayoshi** [comment]
musste süßer mit süsser schreiben, da es sonst das männliche Symbol wird in mc.

Es fehlt noch:
Bild zur Quest:
Name zur Quest:
Name Aufgabe 1:
Name Aufgabe 2:

**Comment by Tsunayoshi** [comment]
im ts geklärt und kommt mit Version 9.0.1.1
