### ISSUE TITLE
Kochen 6 = Marmelade

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#129]
Linke Seite:
Um so Süßer ein Sandwich, desto besser. Deswegen brauchst du jetzt Marmelade. Es gibt sehr viele verschiedene Marmeladen. 

Rechte Seite:
Eine Marmelade wird bekanntermaßen mit Zucker, Früchte und Hitze hergestellt. 
Aufgabe -> detected 8 Marmelade (egal welche)

Belohnung: Auswahl zwischen 3 verschiedenen Marmeladen welche dann jeweils 4 stk haben

Verweise:

**Comment by Tsunayoshi** [comment]
Wieder alle ß durch ss ersetzt. Wird in mc leider nicht richtig angezeigt...


Finde keine marmelade im nei, bitte den englischen begriff dazu schreiben ;)
JELLY SCHUBY - JELLY!

Es fehlt noch:
Quest name:
Bild zur quest:
Name Aufgabe 1:

**Comment by Tsunayoshi** [comment]
oreDict.foodJelly.add(jellyApple);
oreDict.foodJelly.add(jellyBlackberry);
oreDict.foodJelly.add(jellyBlueberry);
oreDict.foodJelly.add(jellyCherry);
oreDict.foodJelly.add(jellyCranberry);
oreDict.foodJelly.add(jellyKiwi);
oreDict.foodJelly.add(jellyLemon);
oreDict.foodJelly.add(jellyLime);
oreDict.foodJelly.add(jellyMango);
oreDict.foodJelly.add(jellyOrange);
oreDict.foodJelly.add(jellyPapaya);
oreDict.foodJelly.add(jellyPeach);
oreDict.foodJelly.add(jellyPomegranate);
oreDict.foodJelly.add(jellyRaspberry);
oreDict.foodJelly.add(jellyStarfruit);
oreDict.foodJelly.add(jellyStrawbeery);
oreDict.foodJelly.add(jellyWatermelon);
oreDict.foodJelly.add(jellyApricot);
oreDict.foodJelly.add(jellyFig);
oreDict.foodJelly.add(jellyGrapefruit);
oreDict.foodJelly.add(jellyPersimon);
oreDict.foodJelly.add(jellyGooseberry);
oreDict.foodJelly.add(jellyPear);
oreDict.foodJelly.add(jellyPlum);

**Comment by Tsunayoshi** [comment]
im ts geklärt und kommt mit Version 9.0.1.1
