### ISSUE TITLE
Kochen 7 Sandwich

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#130]
Linke Seite:
Jetzt hast du endlich alles zusammen für ein sehr süßes Sandwich.

Rechte Seite:
Du musst nur alle Zutaten im Inventar haben, dann kannst du im Cooking Table das passende Sandwich auswählen. Im Kühlschrank kannst du sie dann aufbewahren. (Stellst du ihn an den Cookingtable, kann der Table mit allem was darin ist agieren)

Aufgabe -> detected 8 Sandwiche (egal welche)

Belohnung: Fridge

Verweise:

**Comment by Tsunayoshi** [comment]
ß ersetzt
Sandwich haben keine :ids daher kann man nicht alle unterschiedlichen detecten (fuzzy).
Versuche hier noch eine Lösung per oreDict (oreDict:sandwich geplant) sonst kann es sein, das es nicht geht.

Es fehlt noch:
Name der Quest:
Bild zur Quest:
Name Aufgabe 1:

Frage: 2x Fridge damit man einen großen Kühlschrank bauen kann?
Nur eine - zweite soll selbst gebaut werden.

**Comment by Tsunayoshi** [comment]
oreDict.foodSandwichJelly.add(sandwichJellyApple);
oreDict.foodSandwichJelly.add(sandwichJellyBlackberry);
oreDict.foodSandwichJelly.add(sandwichJellyBlueberry);
oreDict.foodSandwichJelly.add(sandwichJellyCherry);
oreDict.foodSandwichJelly.add(sandwichJellyCranberry);
oreDict.foodSandwichJelly.add(sandwichJellyKiwi);
oreDict.foodSandwichJelly.add(sandwichJellyLemon);
oreDict.foodSandwichJelly.add(sandwichJellyLime);
oreDict.foodSandwichJelly.add(sandwichJellyMango);
oreDict.foodSandwichJelly.add(sandwichJellyOrange);
oreDict.foodSandwichJelly.add(sandwichJellyPapaya);
oreDict.foodSandwichJelly.add(sandwichJellyPeach);
oreDict.foodSandwichJelly.add(sandwichJellyPomegranate);
oreDict.foodSandwichJelly.add(sandwichJellyRaspberry);
oreDict.foodSandwichJelly.add(sandwichJellyStarfruit);
oreDict.foodSandwichJelly.add(sandwichJellyStrawbeery);
oreDict.foodSandwichJelly.add(sandwichJellyWatermelon);
oreDict.foodSandwichJelly.add(sandwichJellyApricot);
oreDict.foodSandwichJelly.add(sandwichJellyFig);
oreDict.foodSandwichJelly.add(sandwichJellyGrapefruit);
oreDict.foodSandwichJelly.add(sandwichJellyPersimon);
oreDict.foodSandwichJelly.add(sandwichJellyGooseberry);
oreDict.foodSandwichJelly.add(sandwichJellyPear);
oreDict.foodSandwichJelly.add(sandwichJellyPlum);

**Comment by Tsunayoshi** [comment]
im ts geklärt und kommt mit Version 9.0.1.1
