### ISSUE TITLE
Regular infuse stone rezept 

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#132]
im aktuellen Rezept muss man einen ganzen weak infusion stone nehmen. Das ist aber problematisch. da man dafür speziel noch einen neuen machen muss. Somit hat man dann nachher 2 weak und 1 regular. das dann für alle anderen Stufen auch. Dadurch hat man dann irgendwann Massen an Weak infusen Stone. Vorher war das anders.

Lösung: 
Rezept so ändern, dass man auch einen benutzten weak infuse Stone benutzen kann.

**Comment by Tsunayoshi** [comment]
ist behoben im nächsten update

**Comment by Tsunayoshi** [comment]
9.0.0.4
