### ISSUE TITLE
Detecting Probleme

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#154]
Wenn Part Builder oder Stencil Table aus einem anderen holz ist, detectet das Questbuch es nicht

**Comment by Tsunayoshi** [comment]
OreDict prüfen

**Comment by Tsunayoshi** [comment]
Hab im Text vermerkt das die Werkbank dann zwei mal gecraftet werden kann um die richtige Bank zu erhalten. Leider ist die andere Bank nicht NBT oder Fuzzy :(

Update 10.2.3.1
