### ISSUE TITLE
BC Quarry deaktivieren

### ISSUE THREAD

**Issue by Tsunayoshi** [Tsunayoshi/Server#20]
Um keinen zu schnellen Start zu haben und Serverlag(Fluid im Steinbruch) (abzuschalten)=>vorzubeugen, die BC Quarry deaktivieren.
Auch auf der Weltkarte besser anzusehen ;)

edit a few times to make it clear ;)

**Comment by asiekierka** [comment]
(If you're having lag issues with the BuildCraft quarry, you might want to consider reporting what exactly is wrong instead of flat-out disabling it.)

**Comment by Tsunayoshi** [comment]
No no, I haven't got any lag with the quarry itself, only with fluids in the quarry hole (minecraft related lags). But this isn't the main reason for disable it, the holes not nice to see in the world (e.g. with dynmap) and with IguanaTinkerTweaks installed the material costs are to low. You can build a quarry to early, so you can skip a few tiers. No problem at all with the quarry ;)

**Comment by Tsunayoshi** [comment]
Will not be deactivated! (Because it's so cool animated!!!)
Recipe change to Signalum, Luminum and Enderium Gear and a Block of Bedrockium instead of redstone.
Update 6.6.2-003

**Comment by Tsunayoshi** [comment]
//VARS
val quarry = <BuildCraft|Builders:machineBlock>;
val bedrockBlock = ExtraUtilities:block_bedrockium;
val skyStoneBurned = appliedenergistics2:tile.BlockSkyStone:1;
val pickhead = TConstruct:pickaxeHead:12;
val gearSignalumOD = ore:gearSignalum;
val gearLumiumOD = ore:gearLumium;
val gearEnderiumOD = ore:gearEnderium;

//RECIPES
//Quarry to endgame
recipes.remove(quarry);
recipes.addShaped(quarry,[
    [gearSignalumOD,    bedrockBlock,       gearSignalumOD],
    [gearLumiumOD,  gearSignalumOD, gearLumiumOD],
    [gearEnderiumOD,    pickhead,           gearEnderiumOD]
]);

=====>> All gears based on diamond gears
Costs at 28 Dias + advanced alloys!
