### ISSUE TITLE
Magical Crops overpowered

### ISSUE THREAD

**Issue by Tsunayoshi** [Tsunayoshi/Server#44]
Seeddrop entfernen und drops reduzieren
bestimmte rezepte entfernen!

**Comment by Attachie** [comment]
Alt?

**Comment by Tsunayoshi** [comment]
Nein. Da Magical Crops eine neue Version bekommen hat und von Grund auf überarbeitet wurde ist der Mod wie ein neuer zu behandeln. Es müsste geprüft werden ob er wie früher ist und wenn ja welche Änderungen sinnvoll sind damit da Mining selbst dennoch interessant bleibt

**Comment by Tsunayoshi** [comment]
Konfig aus SMS konnte übernommen werden. Sollte damit balanced sein.
