### ISSUE TITLE
mining dim

### ISSUE THREAD

**Issue by Tsunayoshi** [Tsunayoshi/Server#78]
flint and steel im rezept. das wurde auf steel angepasst. vielleicht besser auf flint anpassen? damit würde man sofort in die mining dim kommen. ist diese aber peacefull wäre es viel zu einfach.
alternativ so lassen?

**Comment by Attachie** [comment]
würde sagen so lassen mit steel, aber nur wenn man wie du sagtest steel auch ohne Maschienen herstellen kann. kann man automatisches Abbauen irgendwie auf die mining welt beschrenken?

**Comment by Tsunayoshi** [comment]
Zum Autoabbauen:
Ender Quarry: https://github.com/Tsunayoshi/Server/issues/85
Builcraft Quarry: https://github.com/Tsunayoshi/Server/issues/20
Zum Steel:
Botania Altar: https://github.com/Tsunayoshi/Server/issues/75

**Comment by Tsunayoshi** [comment]
Bleibt damit auf Steelnugget
