### ISSUE TITLE
Gepimpte Hamburger haben den falschen Wert bei Pams

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#84]
Wenn ich Hamburger (7397) bastel hat er 3,5 Schenkel.
Upgrade ich ihn mit 7844, dann hat er nur noch 1,5. 
Ebenso beim Upgrade mit 7842.

Also Endprodukte 7874 und 8586 müssen angepasst werden.

**Comment by Tsunayoshi** [comment]
Hungerwerte können nicht bearbeitet werden. U.u. Pam melden - Prüfung steht noch aus

**Comment by Tsunayoshi** [comment]
7397 Hamburger 3,5 3
7847 Onion Hamburger 1,5 0,5
8586 Coleslaw Burger 1,5 0,5

**Comment by Tsunayoshi** [comment]
https://github.com/MatrexsVigil/harvestcraft/issues/11

**Comment by Tsunayoshi** [comment]
Keine Reaktion vom Mod Author. Wurde aber weitergeben.
