### ISSUE TITLE
Tinkers Barren-Cast

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#87]
Man kann nicht mit einem Kupferbarren (6001) einen Cast für die Schmiede herstellen. Ist das beabsichtigt? Habe nun gefundenen Goldbarren benutzt, was ja nicht Sinn der Sache wäre wegen vorgreifen...

**Comment by Tsunayoshi** [comment]
Gold wurde vom TinkersConstruct Mod ersteller hinzugefügt. Normal ist weiterhin Aluminium+Copper zur Legierung Aluminium Brass zu mischen. Damit kann man Casts erstellen. Mit einem Copper AbbauLvl kann man auch Alu abbauen. Sollte also kein Problem sein. Das müsste auch im Buch zur Schmelze (glaube das Schwarze?) stehen, ausser das wurde geändert.

**Comment by Attachie** [comment]
ne also ich habe schon alluminium und Kupfer benutzt für die Mischung, aber um einen barran Cast zu machen, muss man ja einen barren auf den Tisch und dann das Alubrass drüber. und das ging nicht mit einem Kupfer barren nur mit einem Goldbarren

**Comment by Tsunayoshi** [comment]
Aso ja das ist ein Problem weil es kein Minecraftbarren war. Alternativ geht aber auch sein Seared Brick oder ein Clay Brick Barren

**Comment by Attachie** [comment]
ah ok
