### ISSUE TITLE
Modifier Tinkers

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#88]
Ich finde 3 freie Modifier direkt schon am Anfang finde ich zu übertrieben. Die alte Variante, bei der man sich erst einen erarbeiten musste war besser

**Comment by Tsunayoshi** [comment]
Welche Materialieren hast du benutzt?

**Comment by Attachie** [comment]
Kupfer

**Comment by Tsunayoshi** [comment]
Sollte dann nicht der Fall sein. Werde ich testen

**Comment by Tsunayoshi** [comment]
Konig war auf 3. Ist jetzt wieder auf default Wert 0.
Kommt mit Update 6.6.2-005
