### ISSUE TITLE
Anzeige der verbleibenden Haltbarkeit

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#89]
Bei der Picke die Anzeige oben links ist das Prozent oder pro Hit? Glaube nämlich bei Picke ist es Prozent, da sich die Zahl (bei kupfer Picke) nicht pro abgebauten Block ändert. Wäre dann aber unlogisch, da die Rüstung ja über 100 Anzeigt, das kann ja dann kein Prozent sein

**Comment by Tsunayoshi** [comment]
Es sind die Hits die noch übrig sind, es kann aber durch zB. Reinforce dazu kommen das ein Hit nicht abgezogen wird oder durch Moss das die Zahl steigt. Reinforce ist die Chance zu 10% pro Lvl das der Hit nicht abgezogen wird. Daher ist bei Reinforced X auch das Tool unzerstörbar

**Comment by Attachie** [comment]
also das die hit anzeige nicht stimmte war bei meiner Kupfer Picke, die noch garkeine Modifizierung hatte

**Comment by Tsunayoshi** [comment]
Aus welchem Material sind die Teile?

**Comment by Tsunayoshi** [comment]
(-> Kupfer)
Muss ich mal testen

**Comment by Tsunayoshi** [comment]
Du hast recht es ist sozusagen %. Bei Tinkerstools ist es 100, es kann bei anderen Dingen uU. andere Werte annehmen. Die Tinkerstools haben 101 weil der Modauthor sicherstellen wollte das man sieht wann 1% erreicht wurde. Sonst würde dort 0 stehen aber das Tool noch funktionieren. (Damage MetaData 0-100, Author gibt diesen Wert wie folgt aus: 100-DamageMetaValue+1)
Es kann auf diese Art auch vorkommen das Tools, die einen größeren DamageValuePool haben zB. 0-5000, sich anderes verhalten. Grundsätzlich kann man es aber als % sehen, um +1 verschoben.
