### ISSUE TITLE
Hopper

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#90]
Hopper aus stahl??? Warum?

**Comment by Tsunayoshi** [comment]
Hm, ist beabsichtigt, weil mit Eisen frühzeitig eine Automatisierung möglich wäre. Auch das Ausweichen auf Eisenplatten würde nichts bringen, da mit dem Forgehammer diese im normalen Craftingrezept hergestellt werden können. Damit wäre Automatisierung ab einer gelevelten Copper Picke  möglich, ich würde das gerne weiter rauszögern

**Comment by Attachie** [comment]
mh aber so wird man mega gezwungen stahl zu machen und das ist bei mir meist schon endgame

**Comment by Tsunayoshi** [comment]
-> wieder auf Eisenplatten setzen

**Comment by Tsunayoshi** [comment]
Update 6.6.2-004
Ist umgesetzt
