### ISSUE TITLE
Fakeln

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#91]
Von der Idee her nicht schlecht, aber doch sehr nervig wenn die Fakeln ständig draußen und in der Mine ausgehen. Und deswegen zu strom gezwungen zu werden ist nicht so toll

**Comment by Tsunayoshi** [comment]
Wird man nicht. Es gibt viele Lichter ohne Strom, genau gesagt gibt es nur eins mit Strom.
Die Fackeln sind bei mir normale Torches, bei dir Enviromine Torches. Wichtig wäre raus zu bekommen wie die Enviromine Torches gecraftet werden.
Alternatives Licht ist glowstone, Fackeln mit dem Chisel bearbeiten oder auch gregs lightning mod, da gibt es eine lampe mit kohle.
Dennoch sollte das Problem angesehen werden und uU die Enviromine Torches abgeschaltet werden.

**Comment by Tsunayoshi** [comment]
Vermutlich greift Enviromine nur in neu generierte Biome ein, da der Mod erst nachtröglich hinzugefügt wurde wäre das denkbar. damit sind alle davon betroffen. zu teste wäre ob es helfen würde die Rezepte von Davy Lamp und Hard Hat zu ändern!

**Comment by Tsunayoshi** [comment]
Enviromine Fackeln sind überall, Mod funktioniert also. Muss aber alle neu plazieren. Werde das mal machen um das verhalten zu testen

**Comment by Tsunayoshi** [comment]
Sieht sehr nach abschalten aus

**Comment by Tsunayoshi** [comment]
Alternatives Flint & Steel Rezept hinzugefügt:
recipes.addShapeless(flintAsteel.withDamage(48),[ flint, flint, wheat, stick ]);  <------
recipes.addShapeless(flintAsteel.withDamage(32),[ flint, damascusNugget ]);
recipes.addShapeless(flintAsteel,[ flint, steelNugget ]);

Sollte damit zwar nervig aber ok sein. Wenn es zu sehr nervt kann man es immernoch abschalten

**Comment by Tsunayoshi** [comment]
Ja nervig trifft es, wird abgeschaltet: 6.9.0-001
