### ISSUE TITLE
Matallury 4 inkompatibel

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#93]
Kupferbarren von Matallurgy sind in bisher in keine normalen Rezepte kompatibel

**Comment by Tsunayoshi** [comment]
Update eingespielt, teste es noch aus

**Comment by Tsunayoshi** [comment]
Copper und Tin ins Oredictionary eingetragen. Worldgen in Metallurgy für Copper und Tin abgeschaltet.
Silver muss noch geprüft werden

**Comment by Tsunayoshi** [comment]
Problem behoben in Update 6.7
