### ISSUE TITLE
tilled Garden

### ISSUE THREAD

**Issue by Attachie** [Tsunayoshi/Server#99]
Auf Tilled Garden kann man auf einmal keine sticks mehr anbauen

**Comment by Tsunayoshi** [comment]
Folgende Blöcke freigeschaltet:

Botania:enchantedSoil:0
Botany:soil:0
Botany:soil:1
Botany:soil:2
Botany:soil:3
Botany:soil:4
Botany:soil:5
Botany:soil:6
Botany:soil:7
Botany:soil:8
Botany:soilNoWeed:0
Botany:soilNoWeed:1
Botany:soilNoWeed:2
Botany:soilNoWeed:3
Botany:soilNoWeed:4
Botany:soilNoWeed:5
Botany:soilNoWeed:6
Botany:soilNoWeed:7
Botany:soilNoWeed:8
GardenCore:garden_soil
GardenCore:garden_farmland
MineFactoryReloaded:farmland
Natura:soil.tainted:0
Natura:soil.tainted:1
Natura:soil.tainted:2
Thaumcraft:blockTaint:1
TwilightForest:tile.UberousSoil:0
Ztones:cleanDirt:0

**Comment by Tsunayoshi** [comment]
Update 6.9.8

**Comment by Tsunayoshi** [comment]
2 davon funktionieren nicht ist aber auch nicht so schlimm ich lasse es so
